### ISSUE TITLE
Is this only for English?

### ISSUE THREAD

**Issue by adamjleonard** [MartinoMensio/spacy-universal-sentence-encoder-tfhub#2]
I am curious if this can be used with another language as long as the model corresponds to that language? Currently I am doing work in Spanish and have been using the news es model.

Thanks!

**Comment by MartinoMensio** [comment]
Hi Adam! On TF Hub there are are also multilingual models. You can see the full set of Universal Sentence Encoder models here https://tfhub.dev/google/collections/universal-sentence-encoder/1

So you would be interested in one of the following:
- https://tfhub.dev/google/universal-sentence-encoder-multilingual/3 : a model for 16 lanugages
- https://tfhub.dev/google/universal-sentence-encoder-multilingual-large/3 : 16 languages but larger
- https://tfhub.dev/google/universal-sentence-encoder-xling-many/1 : 8 languages
- https://tfhub.dev/google/universal-sentence-encoder-xling/en-es/1 : English and Spanish only

I think I can embed these models in SpaCy wrappers with just a few lines. Which model would you prefer having first?

**Comment by adamjleonard** [comment]
I believe the multilingual is fine, as a lot of the text I am working with actually contains a few things in English.

I'll probably implement, the multilingual-large. I think I can accomplish it, I just wanted to make sure I wasn't missing something other than just loading up one of these models!

**Comment by MartinoMensio** [comment]
Great! This repository is just wrapping these models, so you can use them directly from TF Hub. I am wrapping them together because I would like to have a smooth integration with SpaCy, as it was done for example with [spacy-transformers](https://spacy.io/universe/project/spacy-transformers)

**Comment by MartinoMensio** [comment]
I managed to wrap the first two multilingual models here
- https://github.com/MartinoMensio/spacy-universal-sentence-encoder-tfhub/releases/tag/xx_use_md-0.2.0
- https://github.com/MartinoMensio/spacy-universal-sentence-encoder-tfhub/releases/tag/xx_use_lg-0.2.0

But with the other models I have some issues with a not registered `SentencepieceEncodeSparse` that I cannot make work on my operating system now.
I hope that helps.

**Comment by MartinoMensio** [comment]
Can I consider the issue as solved?
