### ISSUE TITLE
Unable to do pip install. 

### ISSUE THREAD

**Issue by sourcecode369** [MartinoMensio/spacy-universal-sentence-encoder-tfhub#3]
> ERROR: Command errored out with exit status 128: git clone -q ssh://git@github.com/MartinoMensio/spacy-universal-sentence-embedding-tfhub 'C:\Users\ROHIT~1.SIN\AppData\Local\Temp\pip-install-i9wahwsy\universal-sentence-encoder' Check the logs for full command output.

I am getting this error whenever I try to install this using pip.

**Comment by MartinoMensio** [comment]
Hi @sourcecode369 can you provide:

- the specific command you are giving pip
- the logs output (you can use the option `--log log.txt` and then send the lines where it fails

Thanks

**Comment by sourcecode369** [comment]
`ERROR: Command errored out with exit status 128: git clone -q ssh://git@github.com/MartinoMensio/spacy-universal-sentence-embedding-tfhub 'C:\Users\ROHIT~1.SIN\AppData\Local\Temp\pip-install-x7suv_mn\universal-sentence-encoder' Check the logs for full command output.`

I am getting this error, whichever command I try.

>pip install https://github.com/MartinoMensio/spacy-universal-sentence-encoder-tfhub/releases/download/xx_use_lg-0.2.0/xx_use_lg-0.2.0.tar.gz#xx_use_lg-0.2.0

**Comment by MartinoMensio** [comment]
Hi @sourcecode369 ,
Probably you had some problems with git ssh cloning.  Since it requires setting up a public key, I switched the dependency of the models to https, so it should now work smoothly. Please run the command for the new release:

```bash
pip install https://github.com/MartinoMensio/spacy-universal-sentence-encoder-tfhub/releases/download/xx_use_lg-0.2.1/xx_use_lg-0.2.1.tar.gz\#xx_use_lg-0.2.1
```

And let me know if this solves your problem.

Martino

**Comment by MartinoMensio** [comment]
Closed because new versions have been released which fix the ssh cloning.
